from metamodel.cyberThreat.rels.threatPartOf import threatPartOf
from metamodel.cyberThreat.rels.relatedTo import relatedTo
from metamodel.cyberThreat.rels.initiates import initiates
from metamodel.cyberThreat.rels.exploits import exploits
from metamodel.cyberThreat.rels.hasExpertise import hasExpertise
from metamodel.cyberThreat.rels.implementsTTP import implementsTTP
from metamodel.cyberThreat.rels.producesIndicator import producesIndicator
from metamodel.cyberThreat.rels.toolInstanceOf import toolInstanceOf
from metamodel.cyberThreat.rels.hasConfig import hasConfig
from metamodel.cyberThreat.rels.designedFor import designedFor
from metamodel.cyberThreat.rels.targetsSector import targetsSector
from metamodel.cyberThreat.rels.focusesOnCountry import focusesOnCountry
from metamodel.cyberThreat.rels.targetsInternationalBody import targetsInternationalBody
from metamodel.cyberThreat.rels.associatedToTool import associatedToTool
from metamodel.cyberThreat.rels.exploitsVulnerability import exploitsVulnerability
from metamodel.cyberThreat.rels.deploysTool import deploysTool
from metamodel.cyberThreat.rels.softwareVulnerabilityIsA import softwareVulnerabilityIsA
from metamodel.cyberThreat.rels.affectsCode import affectsCode
from metamodel.cyberThreat.rels.compromises import compromises
from metamodel.cyberThreat.rels.hasAdversaryType import hasAdversaryType
from metamodel.cyberThreat.rels.aliasOf import aliasOf
from metamodel.cyberThreat.rels.startsWith import startsWith
from metamodel.cyberThreat.rels.affectsUser import affectsUser
from metamodel.cyberThreat.rels.employsTool import employsTool
from metamodel.cyberThreat.rels.followedBy import followedBy
from metamodel.cyberThreat.rels.requiresConfig import requiresConfig
from metamodel.cyberThreat.rels.requiresExpertise import requiresExpertise
from metamodel.cyberThreat.rels.targetsResource import targetsResource
from metamodel.cyberThreat.rels.violates import violates
from metamodel.cyberThreat.rels.affectsApplication import affectsApplication
from metamodel.cyberThreat.rels.affectsOS import affectsOS
from metamodel.cyberThreat.rels.deployedTo import deployedTo

__all__ = ['threatPartOf', 'relatedTo', 'initiates', 'exploits', 'hasExpertise', 'implementsTTP', 'producesIndicator', 'toolInstanceOf', 'hasConfig', 'designedFor', 'targetsSector', 'focusesOnCountry', 'targetsInternationalBody', 'associatedToTool', 'exploitsVulnerability', 'deploysTool', 'softwareVulnerabilityIsA', 'affectsCode', 'compromises', 'hasAdversaryType', 'aliasOf', 'startsWith', 'affectsUser', 'employsTool', 'followedBy', 'requiresConfig', 'requiresExpertise', 'targetsResource', 'violates', 'affectsApplication', 'affectsOS', 'deployedTo']
